### ISSUE TITLE
param_validator do not cover header, formData param check

### ISSUE THREAD

**Issue by rautenberg** [jphastings/sinatra-swagger#2]
HI,
I know it is a very early stage, but the project looks very promising. As we are about to document some ruby sinatra service APIs with swagger, it looks nice to have features like an automated parameter validation with it. After a first check of the gem:
the parameter types: header and formData seem to be unsupported yet. 

```
parameters:
  - name: bla
    in: header
```

maybe an extension in param_validator.rb  could solve this:

```
parameter = case details['in']
when "query", "header", "formData"
  params[param_name]
```

**Comment by jphastings** [comment]
Indeed it doesn't support those yet - I'll take a look at it :) Feel free to submit a PR if you have the time!
